server:
  port: 9003

spring:
  application:
    name: USER-SERVICE
  cloud:
    consul:
      host: consul
      port: 8500
  sleuth:
    sampler:
      probability: 1.0 # Sample all requests for demonstration purposes

# Zipkin Tracing Configuration
zipkin:
  baseUrl: http://zipkin:9411 # Zipkin Server URL - replace with actual hostname if different

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
